theme: jekyll-theme-slate
markdown: GFM
title: Roswell Investigation & Co.KG
description: If you read this, i have already found you!
plugins:
  - jemoji
main:
  - title: "Main Page"
    url: /index.md
  - title: "About Me"
    url: /aboutme.md
