theme: jekyll-theme-slate
markdown: GFM
title: Roswell Investigation & Co.KG
description: If you read this, i have already found you!
plugins:
  - jemoji
pages_list:       
  About Me: '/aboutme.md'
  Main Page: '/index.md'
